/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a3;

/**
 *
 * @author Pichau
 */
public class tela2 extends javax.swing.JFrame {

    /**
     * Creates new form tela2
     */
    public tela2() {
        initComponents();
    }
double total = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rdbcreme = new javax.swing.JRadioButton();
        rdbbaunilha = new javax.swing.JRadioButton();
        rdbflocos = new javax.swing.JRadioButton();
        rdbmorango = new javax.swing.JRadioButton();
        rdbnapolitano = new javax.swing.JRadioButton();
        rdbvegano = new javax.swing.JRadioButton();
        rdbchocolate = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rdbcaramelocob = new javax.swing.JRadioButton();
        rdbmorangocob = new javax.swing.JRadioButton();
        rdbdocedeleitecob = new javax.swing.JRadioButton();
        rdbchantillycob = new javax.swing.JRadioButton();
        rdbchocolatecob = new javax.swing.JRadioButton();
        rdbleitecondensadocob = new javax.swing.JRadioButton();
        rdbgranuladocob = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        limparsabor = new javax.swing.JButton();
        limparcobertura = new javax.swing.JButton();
        btnconfirmarpedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btncopo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btncasca = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        rdbcreme.setText("Creme - R$ 2,00");
        rdbcreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbcremeActionPerformed(evt);
            }
        });

        rdbbaunilha.setText("Baunilha - R$ 2,00");
        rdbbaunilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbbaunilhaActionPerformed(evt);
            }
        });

        rdbflocos.setText("Flocos - R$ 2,00");
        rdbflocos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbflocosActionPerformed(evt);
            }
        });

        rdbmorango.setText("Morango - R$ 2,00");
        rdbmorango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbmorangoActionPerformed(evt);
            }
        });

        rdbnapolitano.setText("Napolitano - R$ 4,00");
        rdbnapolitano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnapolitanoActionPerformed(evt);
            }
        });

        rdbvegano.setText("Vegano - R$5,00");
        rdbvegano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbveganoActionPerformed(evt);
            }
        });

        rdbchocolate.setText("Chocolate - R$2,00");
        rdbchocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbchocolateActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(51, 204, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setText("      SABORES");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setToolTipText("");

        rdbcaramelocob.setText("Caramelo - R$1,00");
        rdbcaramelocob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbcaramelocobActionPerformed(evt);
            }
        });

        rdbmorangocob.setText("Morango - R$2,00");
        rdbmorangocob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbmorangocobActionPerformed(evt);
            }
        });

        rdbdocedeleitecob.setText("Doce de Leite - R$5,00");
        rdbdocedeleitecob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbdocedeleitecobActionPerformed(evt);
            }
        });

        rdbchantillycob.setText("Chantilly - R$2,00");
        rdbchantillycob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbchantillycobActionPerformed(evt);
            }
        });

        rdbchocolatecob.setText("Chocolate - R$2,00");
        rdbchocolatecob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbchocolatecobActionPerformed(evt);
            }
        });

        rdbleitecondensadocob.setText("Leite Condensado - R$5,00");
        rdbleitecondensadocob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbleitecondensadocobActionPerformed(evt);
            }
        });

        rdbgranuladocob.setText("Granulado - R$4,00");
        rdbgranuladocob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbgranuladocobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbleitecondensadocob, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbgranuladocob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbchocolatecob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbchantillycob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbdocedeleitecob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbmorangocob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbcaramelocob, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbcaramelocob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbmorangocob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbdocedeleitecob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbchantillycob)
                .addGap(12, 12, 12)
                .addComponent(rdbchocolatecob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbleitecondensadocob)
                .addGap(12, 12, 12)
                .addComponent(rdbgranuladocob)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField2.setBackground(new java.awt.Color(51, 204, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setText("   COBERTURAS");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        limparsabor.setBackground(new java.awt.Color(51, 204, 255));
        limparsabor.setText("Limpar Sabor ");
        limparsabor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limparsabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparsaborActionPerformed(evt);
            }
        });

        limparcobertura.setBackground(new java.awt.Color(51, 204, 255));
        limparcobertura.setText("Limpar Coberturas");
        limparcobertura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limparcobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparcoberturaActionPerformed(evt);
            }
        });

        btnconfirmarpedido.setBackground(new java.awt.Color(51, 204, 255));
        btnconfirmarpedido.setText("Confirmar pedido");
        btnconfirmarpedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconfirmarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarpedidoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a3/copo.jpg"))); // NOI18N

        btncopo.setText("Copo");
        btncopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncopoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a3/casca.jpg"))); // NOI18N

        btncasca.setText("Casquinha");
        btncasca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncascaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rdbnapolitano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbcreme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbbaunilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbflocos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbmorango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbvegano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbchocolate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limparcobertura)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limparsabor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btncopo)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnconfirmarpedido))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btncasca)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbcreme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbbaunilha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbflocos)
                        .addGap(12, 12, 12)
                        .addComponent(rdbmorango)
                        .addGap(12, 12, 12)
                        .addComponent(rdbnapolitano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbvegano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbchocolate)
                        .addGap(6, 6, 6))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparcobertura)
                    .addComponent(limparsabor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnconfirmarpedido)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addComponent(btncasca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncopo)))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbveganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbveganoActionPerformed
        // TODO add your handling code here:
        if (rdbvegano.isSelected()) {
            rdbcreme.setSelected(false);
            rdbmorango.setSelected(false);
            rdbchocolate.setSelected(false);
            rdbflocos.setSelected(false);
            rdbbaunilha.setSelected(false);
            rdbnapolitano.setSelected(false);
            total = 5;

        }
    }//GEN-LAST:event_rdbveganoActionPerformed

    private void rdbchocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbchocolateActionPerformed
        // TODO add your handling code here:
        if (rdbchocolate.isSelected()) {
            rdbcreme.setSelected(false);
            rdbflocos.setSelected(false);
            rdbbaunilha.setSelected(false);
            rdbnapolitano.setSelected(false);
            rdbmorango.setSelected(false);
            rdbvegano.setSelected(false);
            total = 2;

        }
    }//GEN-LAST:event_rdbchocolateActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void rdbmorangocobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbmorangocobActionPerformed
        // TODO add your handling code here:
        total += 2;
        rdbmorangocob.setEnabled(false);

        
    }//GEN-LAST:event_rdbmorangocobActionPerformed

    private void rdbdocedeleitecobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbdocedeleitecobActionPerformed
        // TODO add your handling code here:
        total += 5;

        rdbdocedeleitecob.setEnabled(false);

    }//GEN-LAST:event_rdbdocedeleitecobActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void rdbcremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbcremeActionPerformed
        // TODO add your handling code here:
         if (rdbcreme.isSelected()) {
             rdbchocolate.setSelected(false);
             rdbflocos.setSelected(false);
             rdbbaunilha.setSelected(false);
             rdbnapolitano.setSelected(false);
             rdbmorango.setSelected(false);
             rdbvegano.setSelected(false);
             total = 2;
        } 
    }//GEN-LAST:event_rdbcremeActionPerformed

    private void rdbbaunilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbbaunilhaActionPerformed
        // TODO add your handling code here:
        if (rdbbaunilha.isSelected()) {
            rdbcreme.setSelected(false);
            rdbflocos.setSelected(false);
            rdbchocolate.setSelected(false);
            rdbnapolitano.setSelected(false);
            rdbmorango.setSelected(false);
            rdbvegano.setSelected(false);
            total = 2;
        }
    }//GEN-LAST:event_rdbbaunilhaActionPerformed

    private void rdbflocosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbflocosActionPerformed
        // TODO add your handling code here:
        if (rdbflocos.isSelected()) {
            rdbcreme.setSelected(false);
            rdbmorango.setSelected(false);
            rdbchocolate.setSelected(false);
            rdbnapolitano.setSelected(false);
            rdbbaunilha.setSelected(false);
            rdbvegano.setSelected(false);
            total = 2;
        }
    }//GEN-LAST:event_rdbflocosActionPerformed

    private void rdbmorangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbmorangoActionPerformed
        // TODO add your handling code here:
        if (rdbmorango.isSelected()) {
            rdbcreme.setSelected(false);
            rdbflocos.setSelected(false);
            rdbchocolate.setSelected(false);
            rdbnapolitano.setSelected(false);
            rdbbaunilha.setSelected(false);
            rdbvegano.setSelected(false);
            total = 2;
        }
    }//GEN-LAST:event_rdbmorangoActionPerformed

    private void rdbnapolitanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnapolitanoActionPerformed
        // TODO add your handling code here:
        if (rdbnapolitano.isSelected()) {
            rdbcreme.setSelected(false);
            rdbmorango.setSelected(false);
            rdbchocolate.setSelected(false);
            rdbflocos.setSelected(false);
            rdbbaunilha.setSelected(false);
            rdbvegano.setSelected(false);
            total = 4;
        }
    }//GEN-LAST:event_rdbnapolitanoActionPerformed

    private void rdbcaramelocobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbcaramelocobActionPerformed
        // TODO add your handling code here:
        if (rdbcaramelocob.isSelected()) {
            total += 1;
            rdbcaramelocob.setEnabled(false);
        } else{
            total -= 1;   
                    }
        
    }//GEN-LAST:event_rdbcaramelocobActionPerformed

    private void rdbchantillycobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbchantillycobActionPerformed
        // TODO add your handling code here:
      if (rdbchantillycob.isSelected()) {
        total += 2;
         rdbchantillycob.setEnabled(false);
      } else{
          total -= 2;    
              }
           
            
    }//GEN-LAST:event_rdbchantillycobActionPerformed

    private void rdbchocolatecobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbchocolatecobActionPerformed
        // TODO add your handling code here:
        if(rdbchocolatecob.isSelected()){
           total += 2;
        rdbchocolatecob.setEnabled(false);  
        }else{
           total -=2;
        }
       
        
    }//GEN-LAST:event_rdbchocolatecobActionPerformed

    private void rdbleitecondensadocobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbleitecondensadocobActionPerformed
        // TODO add your handling code here:
        if(rdbleitecondensadocob.isSelected());
        total += 5;
        rdbleitecondensadocob.setEnabled(false);
    }//GEN-LAST:event_rdbleitecondensadocobActionPerformed

    private void rdbgranuladocobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbgranuladocobActionPerformed
        // TODO add your handling code here:
        total += 4;
        rdbgranuladocob.setEnabled(false);
    }//GEN-LAST:event_rdbgranuladocobActionPerformed

    private void limparsaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparsaborActionPerformed
        // TODO add your handling code here:
        rdbcreme.setSelected(false);
        rdbmorango.setSelected(false);
        rdbchocolate.setSelected(false);
        rdbnapolitano.setSelected(false);
        rdbbaunilha.setSelected(false);
        rdbflocos.setSelected(false);
        rdbvegano.setSelected(false);
    }//GEN-LAST:event_limparsaborActionPerformed

    private void limparcoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparcoberturaActionPerformed
        // TODO add your handling code here:
         rdbchantillycob.setSelected(false);
        rdbmorangocob.setSelected(false);
        rdbchocolatecob.setSelected(false);
        rdbdocedeleitecob.setSelected(false);
        rdbcaramelocob.setSelected(false);
        rdbleitecondensadocob.setSelected(false);
        rdbgranuladocob.setSelected(false);
        rdbdocedeleitecob.setEnabled(true);
        rdbchocolatecob.setEnabled(true);
        rdbchantillycob.setEnabled(true);
        rdbmorangocob.setEnabled(true);
        rdbcaramelocob.setEnabled(true);
        rdbleitecondensadocob.setEnabled(true);
        rdbgranuladocob.setEnabled(true);
    }//GEN-LAST:event_limparcoberturaActionPerformed

    private void btnconfirmarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarpedidoActionPerformed
        // TODO add your handling code here:
        tela3 novaTela = new tela3();
        novaTela.setVisible(true);
        
    }//GEN-LAST:event_btnconfirmarpedidoActionPerformed

    private void btncopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncopoActionPerformed
        // TODO add your handling code here:
        if (btncopo.isSelected()){
        btncasca.setSelected(false);
    }
        
    }//GEN-LAST:event_btncopoActionPerformed

    private void btncascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncascaActionPerformed
        // TODO add your handling code here:
         if (btncasca.isSelected()){
        btncopo.setSelected(false);
    }
    }//GEN-LAST:event_btncascaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btncasca;
    private javax.swing.JButton btnconfirmarpedido;
    private javax.swing.JRadioButton btncopo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton limparcobertura;
    private javax.swing.JButton limparsabor;
    private javax.swing.JRadioButton rdbbaunilha;
    private javax.swing.JRadioButton rdbcaramelocob;
    private javax.swing.JRadioButton rdbchantillycob;
    private javax.swing.JRadioButton rdbchocolate;
    private javax.swing.JRadioButton rdbchocolatecob;
    private javax.swing.JRadioButton rdbcreme;
    private javax.swing.JRadioButton rdbdocedeleitecob;
    private javax.swing.JRadioButton rdbflocos;
    private javax.swing.JRadioButton rdbgranuladocob;
    private javax.swing.JRadioButton rdbleitecondensadocob;
    private javax.swing.JRadioButton rdbmorango;
    private javax.swing.JRadioButton rdbmorangocob;
    private javax.swing.JRadioButton rdbnapolitano;
    private javax.swing.JRadioButton rdbvegano;
    // End of variables declaration//GEN-END:variables
}
